plugin:
    name: 'numencode.fundamentals::lang.plugin.name'
    description: 'numencode.fundamentals::lang.plugin.description'
    author: 'Blaz Orazem'
    icon: oc-icon-cogs
    homepage: 'https://github.com/numencode/fundamentals-plugin'
